services:
  db-postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=llt_tickets
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  llt.printtickets.poc.api:
    image: llt.printtickets.poc.api
    environment:
      ASPNETCORE_ENVIRONMENT: docker
    ports:
      - '3060:5086'
    build:
      context: .
      dockerfile: src/LLT.PrintTickets.PoC.Api/Dockerfile

volumes:
  db:
    driver: local